In [1]:
%run ./FUNCIONES.ipynb

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
import tabula
from tabula import read_pdf
import numpy as np
import pandas as pd
import re as regex
df = read_pdf('1088877.pdf', guess=False, stream=True, pages='all', multiple_tables=True,  pandas_options={'header':None})

In [4]:
pd.set_option('display.max_colwidth', -1)  #Veo hasta la Ãºltima palabra
pd.set_option('display.max_rows', 1000)

In [6]:
for i in range(len(df)):
    print(i)
    df[i]

0

,0,1,2
0,NaN,Hrs/Rate,Amount
1,9/28/2017 RMW Receive and review and analyze client files,2.10,"1,050.00"
2,NaN,500.00/hr,NaN
3,RMW Review and analyze case file,2.50,"1,250.00"
4,NaN,500 00/hr,NaN
5,RMW Receive and review RO Summary regarding Association,0.30,150.00
6,NaN,500 00/hr,NaN
7,ARS Emails with Attorney Russ Higgins at Knight regarding pre-trial,0.10,32.50
8,conference report,325.00/hr,NaN
9,9/29/2017 ARS Telephone conference with attorney Higgins at Knight Law Group,1.00,32500
10,regarding pre-trial conference,325 00/hr,NaN
11,10/2/2017 ARS Review and revise pre trial conference statement; forward to opposing,2.00,650.00
12,counsel,325.00/hr,NaN
13,ARS Prepare exhibit list,0.50,162.50
14,NaN,325.00/hr,NaN
15,10/26/2017 ARS Receive and review consent order for magistrate,0.10,32.50
16,NaN,325.00/hr,NaN

In [7]:
df = df[0]

In [9]:
df = df.drop(df.head(1).index, axis=0)

In [13]:
rows_per_row = [1,1,1,2,2,2,1,1]
Date, Name, Descripcion = Date_Name_Descripcion(df.loc[:, 0], rows_per_row)
Hours, Rate = Hours_Rates(df.loc[:, 1])
Totals = Totals_func(df.loc[:, 2])

In [15]:
DF = pd.concat([Date.rename('Date'), Name.rename('Names'), Descripcion.rename('Description'),
                     Hours.rename('Hours'), Rate.rename('Rates'), Totals.rename('Totals')], axis=1)

In [16]:
DF

,Date,Names,Description,Hours,Rates,Totals
0,9/28/2017,RMW,Receive and review and analyze client files,2.10,500.0,1050.0
1,9/28/2017,RMW,Review and analyze case file,2.50,500.0,1250.0
2,9/28/2017,RMW,Receive and review RO Summary regarding Association,0.30,500.0,150.0
3,9/28/2017,ARS,Emails with Attorney Russ Higgins at Knight regarding pre-trial conference report,0.10,325.0,32.5
4,9/29/2017,ARS,Telephone conference with attorney Higgins at Knight Law Group regarding pre-trial conference,1.00,325.0,32500.0
5,10/2/2017,ARS,Review and revise pre trial conference statement; forward to opposing counsel,2.00,325.0,650.0
6,10/2/2017,ARS,Prepare exhibit list,0.50,325.0,162.5
7,10/26/2017,ARS,Receive and review consent order for magistrate,0.10,325.0,32.5

In [17]:
DF.to_excel(r"C:\Users\brian\Desktop\trabajillo\\1088877.xlsx", index=False)